"""empty message

Revision ID: 3435216cf672
Revises: 2da6865479a7
Create Date: 2024-12-11 01:22:11.679161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3435216cf672'
down_revision = '2da6865479a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uid', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('email_verify', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email_verify')
        batch_op.drop_column('uid')

    # ### end Alembic commands ###
